version: "2.10.2"
services:
  ui:
    container_name: react
    build:
      context: "."
      dockerfile: Dockerfile
    volumes:
      - '/app'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true